-- Migration: Created the "user" table with auth_user_id linking to auth.users, added full_name and bio fields, and implemented Row Level Security (RLS) policies so users can only view and edit their own profiles.
-- Executed at: 2026-03-10T04:43:07Z
-- Generated by AI Agent

CREATE TABLE IF NOT EXISTS "user" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  bio TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT user_auth_user_id_key UNIQUE (auth_user_id)
);

-- Enable Row Level Security
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;

-- Create policies to ensure users can only access their own data
DROP POLICY IF EXISTS "Users can view own profile" ON "user";
CREATE POLICY "Users can view own profile" ON "user"
  FOR SELECT USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Users can update own profile" ON "user";
CREATE POLICY "Users can update own profile" ON "user"
  FOR UPDATE USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Users can insert own profile" ON "user";
CREATE POLICY "Users can insert own profile" ON "user"
  FOR INSERT WITH CHECK (auth.uid() = auth_user_id);
