-- Migration: Add 'handicap' column to the 'user' table to store the user's golf handicap.
-- Executed at: 2026-03-10T04:59:02Z
-- Generated by AI Agent

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS handicap NUMERIC(4,1);
