-- Migration: Created the 'course_tee_header' table to store tees for each course, including a 'color' field for the hex code. Added RLS policies and inserted sample tees for existing courses.
-- Executed at: 2026-03-10T05:26:57Z
-- Generated by AI Agent

DO $$
DECLARE
  course_id_type text;
  tee_count int;
BEGIN
  -- Check the data type of course_header.id to match the foreign key type
  SELECT data_type INTO course_id_type
  FROM information_schema.columns
  WHERE table_name = 'course_header' AND column_name = 'id';

  IF course_id_type = 'uuid' THEN
    EXECUTE 'CREATE TABLE IF NOT EXISTS course_tee_header (
      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
      course_id UUID REFERENCES course_header(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      color TEXT NOT NULL
    )';
  ELSE
    EXECUTE 'CREATE TABLE IF NOT EXISTS course_tee_header (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      course_id BIGINT REFERENCES course_header(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      color TEXT NOT NULL
    )';
  END IF;

  -- Check if we already have data to avoid duplicates
  SELECT count(*) INTO tee_count FROM course_tee_header;

  IF tee_count = 0 THEN
    -- Insert sample tees for existing courses
    INSERT INTO course_tee_header (course_id, name, color)
    SELECT id, 'Championship (Black)', '#000000' FROM course_header WHERE name ILIKE '%Championship%';

    INSERT INTO course_tee_header (course_id, name, color)
    SELECT id, 'Standard (White)', '#FFFFFF' FROM course_header;

    INSERT INTO course_tee_header (course_id, name, color)
    SELECT id, 'Forward (Red)', '#FF0000' FROM course_header;

    INSERT INTO course_tee_header (course_id, name, color)
    SELECT id, 'Pro (Blue)', '#0000FF' FROM course_header;
  END IF;
END $$;

ALTER TABLE course_tee_header ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON course_tee_header;
CREATE POLICY "Enable read access for all users" ON course_tee_header FOR SELECT USING (true);
