-- Migration: Created the 'club' table to store golf clubs, enabled Row Level Security (RLS) for authenticated users to read, and inserted some sample golf clubs so the autocomplete has data to search.
-- Executed at: 2026-03-10T04:55:27Z
-- Generated by AI Agent

CREATE TABLE IF NOT EXISTS club (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL
);

-- Enable Row Level Security
ALTER TABLE club ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access to authenticated users" ON club
  FOR SELECT TO authenticated USING (true);

-- Insert some sample golf clubs for testing
INSERT INTO club (name) VALUES
  ('Augusta National Golf Club'),
  ('Pine Valley Golf Club'),
  ('Cypress Point Club'),
  ('Shinnecock Hills Golf Club'),
  ('Oakmont Country Club'),
  ('Pebble Beach Golf Links'),
  ('St. Andrews Links'),
  ('Muirfield'),
  ('Royal County Down Golf Club'),
  ('Royal Melbourne Golf Club');
