// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: xalfhenbzqllfairjdih

class SupabaseConfig {
  static const String supabaseUrl = 'https://xalfhenbzqllfairjdih.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbGZoZW5ienFsbGZhaXJqZGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NTM5NzksImV4cCI6MjA4NzQyOTk3OX0.92OrCcc6j9FSvCTvit5ljDx0vzqAtSj9nXZY2U5TMRA';
}
